This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./exerciseglossaries.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file exerciseglossaries.acn....done (2 entries accepted, 0 rejected).
Sorting entries....done (2 comparisons).
Generating output file exerciseglossaries.acr....done (6 lines written, 0 warnings).
Output written in exerciseglossaries.acr.
Transcript written in exerciseglossaries.alg.
