This is makeindex, version 2.15 [TeX Live 2013] (kpathsea + Thai support).
Scanning style file ./Thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Thesis.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file Thesis.acr....done (9 lines written, 0 warnings).
Output written in Thesis.acr.
Transcript written in Thesis.alg.
